# Generated by Django 5.2.7 on 2026-03-11 19:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentdocument',
            name='track',
            field=models.CharField(choices=[('ALL', 'All Tracks'), ('IR', 'International Relations'), ('CP', 'Comparative Politics'), ('LGP', 'Liberian Government & Politics')], default='ALL', max_length=20),
        ),
        migrations.AddField(
            model_name='librarybook',
            name='track',
            field=models.CharField(choices=[('ALL', 'All Tracks'), ('IR', 'International Relations'), ('CP', 'Comparative Politics'), ('LGP', 'Liberian Government & Politics')], default='ALL', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='studentelective',
            unique_together={('student', 'course', 'semester', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='studentminor',
            unique_together={('student', 'course', 'semester', 'year')},
        ),
        migrations.CreateModel(
            name='GradeRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grade', models.CharField(choices=[('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('D', 'D'), ('F', 'F'), ('IP', 'In Progress')], max_length=2)),
                ('semester', models.CharField(choices=[('fall', 'Fall'), ('spring', 'Spring'), ('summer', 'Summer')], max_length=10)),
                ('year', models.IntegerField()),
                ('date_recorded', models.DateField(default=django.utils.timezone.now)),
                ('is_completed', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_records', to='department.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_records', to='department.student')),
            ],
            options={
                'ordering': ['-year', '-semester', '-date_recorded'],
                'unique_together': {('student', 'course', 'semester', 'year')},
            },
        ),
    ]
