# Generated by Django 5.2.7 on 2026-03-13 00:33

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_departmentdocument_track_librarybook_track_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentelective',
            unique_together={('student', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='studentminor',
            unique_together={('student', 'course')},
        ),
        migrations.AddField(
            model_name='student',
            name='county',
            field=models.CharField(blank=True, choices=[('bomi', 'Bomi'), ('bong', 'Bong'), ('gbarpolu', 'Gbarpolu'), ('grand_bassa', 'Grand Bassa'), ('grand_cape_mount', 'Grand Cape Mount'), ('grand_gedeh', 'Grand Gedeh'), ('grand_kru', 'Grand Kru'), ('lofa', 'Lofa'), ('margibi', 'Margibi'), ('maryland', 'Maryland'), ('montserrado', 'Montserrado'), ('nimba', 'Nimba'), ('river_cess', 'River Cess'), ('river_ghee', 'River Gee'), ('sinoe', 'Sinoe')], help_text='County of origin in Liberia', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='nationality',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='program_type',
            field=models.CharField(choices=[('major', 'Major'), ('minor', 'Minor')], default='major', help_text='Whether student is majoring or minoring in the department', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='religion',
            field=models.CharField(blank=True, choices=[('Christianity', 'Christianity'), ('Islam', 'Islam'), ('Traditional', 'Traditional African Religion'), ('Other', 'Other'), ('None', 'None')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='county',
            field=models.CharField(blank=True, choices=[('bomi', 'Bomi'), ('bong', 'Bong'), ('gbarpolu', 'Gbarpolu'), ('grand_bassa', 'Grand Bassa'), ('grand_cape_mount', 'Grand Cape Mount'), ('grand_gedeh', 'Grand Gedeh'), ('grand_kru', 'Grand Kru'), ('lofa', 'Lofa'), ('margibi', 'Margibi'), ('maryland', 'Maryland'), ('montserrado', 'Montserrado'), ('nimba', 'Nimba'), ('river_cess', 'River Cess'), ('river_ghee', 'River Gee'), ('sinoe', 'Sinoe')], help_text='County of origin in Liberia', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='nationality',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='religion',
            field=models.CharField(blank=True, choices=[('Christianity', 'Christianity'), ('Islam', 'Islam'), ('Traditional', 'Traditional African Religion'), ('Other', 'Other'), ('None', 'None')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='graderecord',
            name='semester',
            field=models.CharField(choices=[('semester1', 'Semester 1'), ('semester2', 'Semester 2')], max_length=10),
        ),
        migrations.AlterField(
            model_name='studentelective',
            name='semester',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentelective',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentminor',
            name='semester',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentminor',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacherassignment',
            name='semester',
            field=models.CharField(choices=[('semester1', 'Semester 1'), ('semester2', 'Semester 2')], default='semester1', max_length=10),
        ),
    ]
