# Generated by Django 5.2.7 on 2026-03-14 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0004_userrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('admin', 'Chairman'), ('teacher', 'Record Officer'), ('clearing', 'Clearing Officer'), ('Administrative', 'Administrative Assistance')], default='teacher', help_text="User's role in the system", max_length=20),
        ),
    ]
