# Generated by Django 5.2.7 on 2026-03-15 11:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0005_alter_userrole_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('chairman', 'Chairman'), ('teacher', 'Record Officer'), ('clearing', 'Clearing Officer'), ('assistant', 'Administrative Assistant')], default='teacher', help_text="User's role in the system", max_length=20),
        ),
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('new_password', models.CharField(blank=True, max_length=128, null=True)),
                ('was_successful', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reset_at', models.DateTimeField(auto_now=True)),
                ('reset_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='password_resets_initiated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_resets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
