# Generated by Django 5.2.7 on 2026-03-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0006_alter_userrole_role_passwordreset'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='additional_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='chairman_name',
            field=models.CharField(default='Assistant Professor, Richmond S. Anderson', max_length=200),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='chairman_signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='chairman_title',
            field=models.CharField(default='Department Chair', max_length=200),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='department_logo',
            field=models.ImageField(blank=True, null=True, upload_to='settings/'),
        ),
    ]
